<?php
 return array (
  'safe_mode_enable' => 0,
  'stop_register' => 0,
  'email_verify' => 0,
  'app_name' => '',
  'app_description' => '',
  'app_url' => 'https://techzpn.pro',
  'subscribe_url' => 'https://techzpn.pro',
  'try_out_plan_id' => 0,
  'try_out_hour' => 1,
  'email_whitelist_enable' => 0,
  'email_whitelist_suffix' => 
  array (
    0 => 'gmail.com',
  ),
  'email_gmail_limit_enable' => 0,
  'recaptcha_enable' => 0,
  'recaptcha_key' => '6LccMfYnAAAAAMi0inASa8ifJeNc_aEhYCewG_fc',
  'recaptcha_site_key' => '6LccMfYnAAAAAKiJwLdZpdNcwfHGWaCn19w9FTuL',
  'tos_url' => '',
  'frontend_theme' => 'techzpn',
  'frontend_theme_sidebar' => 'light',
  'frontend_theme_header' => 'light',
  'frontend_theme_color' => 'default',
  'frontend_background_url' => 'https://techzpn.pro/theme/GIF/logo.gif',
  'frontend_admin_path' => 'admin',
  'frontend_customer_service_method' => '0',
  'frontend_customer_service_id' => '',
  'invite_force' => 0,
  'invite_commission' => 20,
  'invite_gen_limit' => 1,
  'invite_never_expire' => 0,
  'commission_first_time_enable' => 0,
  'commission_auto_check_enable' => 1,
  'commission_withdraw_limit' => 50000,
  'commission_withdraw_method' => 
  array (
    0 => 'Momo',
    1 => 'Bank',
  ),
  'withdraw_close_enable' => 0,
  'server_token' => 'admin@techzpn.pro',
  'server_license' => NULL,
  'server_log_enable' => 0,
  'server_v2ray_domain' => NULL,
  'server_v2ray_protocol' => NULL,
  'email_template' => 'techzpn',
  'email_host' => 'smtp.gmail.com',
  'email_port' => 587,
  'email_username' => 'hotro.autosubre@gmail.com',
  'email_password' => 'fvszzratvdgijbpt',
  'email_encryption' => 'TLS',
  'email_from_address' => 'hotro.autosubre@gmail.com',
  'telegram_bot_enable' => 1,
  'telegram_bot_token' => '6626590610:AAFHfU83ExusHuhyzemZp0ESJYMh5I3KiYc',
  'plan_change_enable' => 1,
  'reset_traffic_method' => 1,
  'surplus_enable' => 0,
  'email_rate_limit' => 100,
  'telegram_discuss_link' => 'https://t.me/speed4gtore',
  'server_vmess_domain' => NULL,
  'server_vmess_protocol' => NULL,
  'frontend_world_fill_color' => '#4caf50',
  'frontend_world_marker_color' => '#4caf50',
  'rate_limit_per_minute' => 10,
  'subscribe_cache_enable' => 1,
) ;